/* NeedBridge — TR/EN Language System */

const LANG = {
  en: {
    nav: {
      problems: 'Problem Board',
      solvers: 'Solver Directory',
      how: 'How It Works',
      pricing: 'Pricing',
      signin: 'Sign in',
      join: 'Join free →',
    },
    footer: {
      desc: 'The platform where corporate problems meet startup solutions.',
      platform: 'Platform',
      seekers: 'For Seekers',
      solvers: 'For Solvers',
      links: {
        problems: 'Problem Board',
        solvers: 'Solver Directory',
        how: 'How It Works',
        pricing: 'Pricing',
        post: 'Post a problem',
        browse: 'Browse problems',
        seekerHow: 'Seeker guide',
        trust: 'Trust & safety',
        profile: 'Create profile',
        apply: 'Apply to problems',
        solverHow: 'Solver guide',
        badge: 'Verified badge',
      },
      copy: '© 2026 NeedBridge. All rights reserved.',
      privacy: 'Privacy',
      terms: 'Terms',
      contact: 'Contact',
    },
    index: {
      eyebrow: 'A new platform for corporate innovation',
      h1: 'Your company needs a solution.',
      h1b: 'A startup has it.',
      h1em: 'NeedBridge connects them.',
      desc: 'Large and mid-size companies publish procurement problems anonymously. Startups and innovators from around the world apply with their solutions — software, hardware, systems, machinery, or anything in between.',
      cta_seeker: 'Post a problem →',
      cta_solver: 'Offer a solution',
      early_tag: 'Early access — free until October 2026',
      role_seeker_title: 'For Seekers',
      role_seeker_sub: 'You have a procurement problem',
      role_seeker_desc: 'Any department, any need. Publish your problem anonymously. Your company name stays hidden until you choose to reveal it. Receive structured proposals from vetted startups and set up a pilot — all on one platform.',
      role_seeker_feats: [
        'Anonymous listing — company name protected',
        'Receive structured proposals from startups',
        'Pilot escrow protection for both sides',
        'Zero commission for companies — ever',
      ],
      role_solver_title: 'For Solvers',
      role_solver_sub: 'You have a solution to offer',
      role_solver_desc: 'Browse real corporate procurement needs. Submit proposals without revealing your identity. Track every application in your pipeline. Build a verified reputation with every closed deal.',
      role_solver_feats: [
        'Google-indexed profile from day one',
        'Full problem details and requirements',
        '90-day protection against dead listings',
        'Verified Supplier badge on closed deals',
      ],
      how_tag: 'How it works',
      how_h: 'Simple. Transparent.',
      how_em: 'Protected.',
      how_d: 'The same platform serves both sides — with a process designed to protect everyone from first contact to closed deal.',
      tab_seeker: '🏢 As a Seeker',
      tab_solver: '🚀 As a Solver',
      seeker_steps: [
        { label: 'Post', title: 'Publish your problem', desc: 'Describe what you need — any sector, any solution type. Set a budget range and deadline. Your company name is anonymous until you approve a meeting.', note: 'Free to post · Company name protected' },
        { label: 'Review', title: 'Receive proposals', desc: 'Startups apply with their solution summary, pricing, and timeline. You review proposals — but not their identities — until you\'re ready to meet.', note: 'Average 8–15 proposals per listing' },
        { label: 'Meet', title: 'Schedule a meeting on-platform', desc: 'Invite the startups you like. Every meeting is logged — creating a legal record of the introduction. Identities are revealed at this stage.', note: 'All meetings documented on platform' },
        { label: 'Pilot', title: 'Run a protected pilot', desc: 'Agree on scope and payment. The pilot fee goes into escrow and is released when the startup delivers. No payment risk for either side.', note: '🔒 Escrow protection' },
        { label: 'Close', title: 'Sign and close the deal', desc: 'Manage the contract through NeedBridge. The full process is documented in your Innovation Dashboard. Zero commission for Seekers.', note: '€0 commission for Seekers' },
      ],
      solver_steps: [
        { label: 'Profile', title: 'Build your profile', desc: 'Add your solution categories, industries, and case studies. Your profile is indexed on Google from day one — organic visibility without paid ads.', note: 'Google-indexed from day one' },
        { label: 'Discover', title: 'Find matching problems', desc: 'Filter by category, budget, region, and solution type. Get weekly email alerts for new problems in your areas.', note: 'Weekly email alerts' },
        { label: 'Apply', title: 'Submit your proposal', desc: 'Send your pricing, timeline, and solution summary. Your identity stays hidden until the company formally approves a meeting.', note: 'Identity hidden until meeting approved' },
        { label: 'Track', title: 'Track your pipeline', desc: 'See every application\'s stage in real time. If a company goes silent for 90 days, the platform alerts them — protecting you from wasted effort.', note: '🛡️ 90-day protection rule' },
        { label: 'Close', title: 'Deliver and get paid', desc: 'Pilot payment held in escrow, released when you deliver. Every closed deal adds a verified reference to your profile.', note: 'Escrow payment guarantee' },
      ],
      li_tag: 'LinkedIn integration',
      li_h: 'Seekers can share problems directly on LinkedIn.',
      li_em: 'directly on LinkedIn.',
      li_d: 'When you post a problem on NeedBridge, share it to your professional network with one click. Your startup connections see it, apply, and the problem gets solved faster.',
      li_btn: 'Share on LinkedIn',
      trust_tag: 'Trust & safety',
      trust_h: 'Built so neither side',
      trust_em: 'can bypass the platform.',
      trust_d: 'Five interlocking mechanisms make staying on NeedBridge more valuable than leaving it.',
      trust_items: [
        { icon: '🎭', title: 'Proposal anonymity', desc: 'Companies see solution pitches — not solver identities. Solvers see the problem — not the company name. Identities revealed only on meeting approval.', eff: '→ The introduction happens on NeedBridge' },
        { icon: '📋', title: 'Meeting records', desc: 'Every meeting is logged — date, time, participants. This creates a legal record of the introduction, backed by a 24-month membership clause.', eff: '→ Bypassing creates legal risk' },
        { icon: '🔒', title: 'Pilot escrow', desc: 'Pilot payment held in platform escrow. Released automatically when the solver delivers. If delivery fails, the fee returns to the company.', eff: '→ Deliver first, payment follows' },
        { icon: '⏱️', title: '90-day action rule', desc: 'Automated alerts at 30, 60, and 90 days after a budget discussion. At day 90 with no action, the listing suspends and the commitment deposit is forfeited.', eff: '→ Dead listings cost money' },
        { icon: '⭐', title: 'Solver reputation lock', desc: 'Verified badge, reference score, and priority matching are platform-exclusive. Bypassing loses this reputation permanently.', eff: '→ Long-term cost of leaving' },
      ],
      cta_tag: 'Join NeedBridge',
      cta_h: 'Be among the first.',
      cta_em: 'Free until October 2026.',
      cta_d: 'We\'re building something new. Every feature is free while we grow. No credit card, no commitment — join as a Seeker or Solver and start connecting today.',
      cta_role_s: '🏢 I\'m a Seeker',
      cta_role_sv: '🚀 I\'m a Solver',
      cta_btn: 'Join free →',
      cta_note: 'Free until October 2026 · No spam · Cancel anytime',
    },
    problems: {
      eyebrow: 'Problem Board',
      h1: 'Real problems.',
      h1em: 'Open for solutions.',
      desc: 'Companies publish procurement needs anonymously. Every listing has a defined budget, deadline, and solution type. Join as a Solver to see all listings and apply.',
      example_notice: 'These are example listings to show how the platform works. Real listings appear when companies join.',
      filter_placeholder: 'Search problems, sectors, technologies...',
      all: 'All',
      paywall_title: 'Join as a Solver to see all listings',
      paywall_sub: 'Free until October 2026. Browse, apply, and connect — no payment needed.',
      paywall_btn: 'Join free as a Solver →',
      apply_btn: 'Details & Apply',
      save_btn: 'Save',
      apps: 'applications',
      pilot_ok: 'Pilot OK',
      seeker_box_title: 'Are you a Seeker?',
      seeker_box_desc: 'Post your procurement problem and reach innovative startups. Free.',
      seeker_box_btn: 'Post a problem →',
      urgent: 'Urgent',
      open: 'Open',
      review: 'Under review',
    },
    solvers: {
      eyebrow: 'Solver Directory',
      h1: 'The startups solving corporate problems.',
      h1em: 'Global.',
      desc: 'Browse startups and innovators by solution category, technology, and region. Join as a Seeker to connect.',
      example_notice: 'These are example profiles to show how the platform works. Real solver profiles appear when startups join.',
      add_btn: 'Add your startup →',
      filter_placeholder: 'Search solvers, technologies...',
      all: 'All',
      new_week: '✨ New this week',
      view: 'View profile',
      connect: 'Connect',
      verified: '✓ Verified',
      paywall_title: 'Join as a Seeker to connect with solvers',
      paywall_sub: 'Free until October 2026.',
      paywall_btn: 'Join free as a Seeker →',
    },
    join: {
      tag: 'Early access',
      h1: 'Create your account',
      sub: 'Free until October 2026. No credit card needed.',
      left_h: 'The platform where corporate problems meet startup solutions.',
      left_d: 'Join as a Seeker to post problems anonymously. Join as a Solver to offer your solutions and build a verified reputation.',
      tab_solver: '🚀 I\'m a Solver',
      tab_seeker: '🏢 I\'m a Seeker',
      name: 'Full name',
      email: 'Work email',
      company: 'Company / Startup name',
      cat: 'Primary solution category',
      sector: 'Your industry',
      country: 'Country',
      submit: 'Create free account →',
      terms: 'By joining you agree to our',
      terms_link: 'Terms of Service',
      and: 'and',
      privacy_link: 'Privacy Policy',
      or: 'or',
      li_btn: 'Continue with LinkedIn',
      success_h: 'You\'re on the list!',
      success_d: 'Welcome to NeedBridge early access. We\'ll send you an activation link within 24 hours.',
      note: 'Free until October 2026 · No spam · Cancel anytime',
    },
    pricing: {
      tag: 'Pricing',
      h1: 'Start free.',
      h1em: 'Grow together.',
      desc: 'Free for everyone until October 2026. After that, a simple model: Seekers always post for free. Solvers pay to connect and grow.',
      free_alert: '🎉 Early access: Every feature is free until October 2026. No credit card required.',
      free_pill: 'Free until Oct 2026',
      monthly: 'Monthly',
      annual: 'Annual',
      save: 'Save 20%',
      tab_solver: '🚀 Solver plans',
      tab_seeker: '🏢 Seeker plans',
    },
  },

  tr: {
    nav: {
      problems: 'Problem Panosu',
      solvers: 'Çözüm Üreticiler',
      how: 'Nasıl Çalışır',
      pricing: 'Fiyatlandırma',
      signin: 'Giriş yap',
      join: 'Ücretsiz katıl →',
    },
    footer: {
      desc: 'Kurumsal problemlerin startup çözümleriyle buluştuğu platform.',
      platform: 'Platform',
      seekers: 'Şirketler için',
      solvers: 'Çözüm Üreticiler için',
      links: {
        problems: 'Problem Panosu',
        solvers: 'Çözüm Üretici Vitrini',
        how: 'Nasıl Çalışır',
        pricing: 'Fiyatlandırma',
        post: 'Problem ilanı aç',
        browse: 'Problemlere göz at',
        seekerHow: 'Şirket rehberi',
        trust: 'Güven ve güvenlik',
        profile: 'Profil oluştur',
        apply: 'Problemlere başvur',
        solverHow: 'Çözüm üretici rehberi',
        badge: 'Doğrulanmış rozet',
      },
      copy: '© 2026 NeedBridge. Tüm hakları saklıdır.',
      privacy: 'Gizlilik',
      terms: 'Kullanım Şartları',
      contact: 'İletişim',
    },
    index: {
      eyebrow: 'Kurumsal inovasyon için yeni bir platform',
      h1: 'Şirketinizin ihtiyacı var.',
      h1b: 'Bir startup\'ın çözümü var.',
      h1em: 'NeedBridge ikisini buluşturuyor.',
      desc: 'Büyük ve orta ölçekli şirketler tedarik ihtiyaçlarını anonim olarak yayınlar. Dünyanın dört bir yanından startup\'lar ve inovatörler — yazılım, donanım, sistem, makina veya her ne olursa — çözüm önerir.',
      cta_seeker: 'Problem ilanı aç →',
      cta_solver: 'Çözüm sun',
      early_tag: 'Erken erişim — Ekim 2026\'ya kadar ücretsiz',
      role_seeker_title: 'Şirketler için',
      role_seeker_sub: 'Bir tedarik probleminiz var',
      role_seeker_desc: 'Her departman, her ihtiyaç. Probleminizi anonim olarak yayınlayın. Şirket adınız, siz onaylayana kadar gizli kalır. Startup\'lardan yapılandırılmış teklifler alın ve pilotu tek platformdan yönetin.',
      role_seeker_feats: [
        'Anonim ilan — şirket adı korumalı',
        'Startup\'lardan yapılandırılmış teklifler alın',
        'Her iki taraf için pilot escrow güvencesi',
        'Şirketlere komisyon yok — hiçbir zaman',
      ],
      role_solver_title: 'Çözüm Üreticiler için',
      role_solver_sub: 'Sunabileceğiniz bir çözümünüz var',
      role_solver_desc: 'Gerçek kurumsal tedarik ihtiyaçlarına göz atın. Kimliğinizi açıklamadan teklif gönderin. Her başvurunuzu pipeline\'ınızda takip edin. Kapanan her anlaşmayla doğrulanmış bir itibar oluşturun.',
      role_solver_feats: [
        'İlk günden Google\'da indexlenen profil',
        'Tam problem tanımı ve gereksinimler',
        'Ölü ilanlara karşı 90 gün koruması',
        'Kapanan anlaşmalarda Doğrulanmış Tedarikçi rozeti',
      ],
      how_tag: 'Nasıl çalışır',
      how_h: 'Basit. Şeffaf.',
      how_em: 'Korumalı.',
      how_d: 'Aynı platform her iki tarafa da hizmet eder — ilk temassandan anlaşma kapanışına kadar herkesi koruyan bir süreçle.',
      tab_seeker: '🏢 Şirket olarak',
      tab_solver: '🚀 Çözüm Üretici olarak',
      seeker_steps: [
        { label: 'İlan', title: 'Probleminizi yayınlayın', desc: 'Ne ihtiyacınız olduğunu tanımlayın — sektör fark etmez, çözüm tipi fark etmez. Bütçe aralığı ve son tarih belirleyin. Şirket adınız, siz bir görüşmeyi onaylayana kadar anonimdir.', note: 'Ücretsiz ilan · Şirket adı korumalı' },
        { label: 'İnceleme', title: 'Teklifleri inceleyin', desc: 'Startup\'lar çözüm özetleri, fiyatlandırma ve zaman çizelgesiyle başvurur. Teklifleri incelersiniz — ama kimliklerini değil — görüşmeye hazır olana kadar.', note: 'İlan başına ort. 8–15 başvuru' },
        { label: 'Görüşme', title: 'Platform üzerinden görüşme ayarlayın', desc: 'Beğendiklerinizi görüşmeye davet edin. Her görüşme kayıt altına alınır — tanışmanın yasal kaydını oluşturur. Kimlikler bu aşamada açılır.', note: 'Tüm görüşmeler platformda kayıtlı' },
        { label: 'Pilot', title: 'Korumalı pilot çalışma başlatın', desc: 'Kapsam ve ödeme üzerinde mutabık kalın. Pilot ücreti escrow\'a alınır ve startup teslim ettiğinde otomatik serbest bırakılır.', note: '🔒 Escrow güvencesi' },
        { label: 'Anlaşma', title: 'İmzalayın ve anlaşmayı kapatın', desc: 'Sözleşmeyi NeedBridge üzerinden yönetin. Sürecin tamamı İnovasyon Panelinizde kayıtlı. Şirketlere komisyon yok.', note: 'Şirketlere €0 komisyon' },
      ],
      solver_steps: [
        { label: 'Profil', title: 'Profilinizi oluşturun', desc: 'Çözüm kategorilerinizi, sektörlerinizi ve referans projelerinizi ekleyin. Profiliniz ilk günden Google\'da indexlenir.', note: 'İlk günden Google\'da indexlenir' },
        { label: 'Keşfet', title: 'Eşleşen problemleri bulun', desc: 'Kategori, bütçe, bölge ve çözüm tipine göre filtreleyin. Kategorilerinizdeki yeni problemler için haftalık e-posta bildirimi alın.', note: 'Haftalık e-posta bildirimi' },
        { label: 'Başvur', title: 'Teklifinizi gönderin', desc: 'Fiyatlandırma, zaman çizelgesi ve çözüm özetinizi gönderin. Kimliğiniz, şirket resmi olarak bir görüşmeyi onaylayana kadar gizli kalır.', note: 'Görüşme onaylanana kadar kimlik gizli' },
        { label: 'Takip', title: 'Pipeline\'ınızı takip edin', desc: 'Her başvurunun aşamasını gerçek zamanlı görün. Bir şirket 90 gün sessiz kalırsa platform onları uyarır — sizi boşa harcanan çabadan korur.', note: '🛡️ 90 gün koruma kuralı' },
        { label: 'Anlaşma', title: 'Teslim edin ve ödemenizi alın', desc: 'Pilot ödemesi escrow\'da tutulur, teslim ettiğinizde serbest bırakılır. Kapanan her anlaşma profilinize doğrulanmış referans ekler.', note: 'Escrow ödeme güvencesi' },
      ],
      li_tag: 'LinkedIn entegrasyonu',
      li_h: 'Şirketler problemlerini',
      li_em: 'doğrudan LinkedIn\'de paylaşabilir.',
      li_d: 'NeedBridge\'de problem ilanı açtığınızda, tek tıkla profesyonel ağınızla paylaşın. Startup bağlantılarınız görür, başvurur ve problem daha hızlı çözülür.',
      li_btn: 'LinkedIn\'de paylaş',
      trust_tag: 'Güven ve güvenlik',
      trust_h: 'Hiçbir tarafın',
      trust_em: 'sistemi atlayamayacağı bir yapı.',
      trust_d: 'Birbiriyle kilitli beş mekanizma, NeedBridge\'de kalmayı terk etmekten çok daha değerli kılar.',
      trust_items: [
        { icon: '🎭', title: 'Başvuru anonimliği', desc: 'Şirketler çözüm tekliflerini görür — çözüm üretici kimliklerini değil. Kimlikler yalnızca görüşme onayında açılır.', eff: '→ Tanışma NeedBridge\'de gerçekleşir' },
        { icon: '📋', title: 'Görüşme kayıtları', desc: 'Her görüşme kayıt altına alınır. Bu, tanışmanın yasal kanıtını oluşturur; 24 aylık üyelik maddesiyle desteklenir.', eff: '→ Platformu atlamak yasal risk yaratır' },
        { icon: '🔒', title: 'Pilot escrow', desc: 'Pilot ödemesi platform escrow\'unda tutulur. Çözüm üretici teslim ettiğinde otomatik serbest bırakılır. Başarısızlıkta ücret iade edilir.', eff: '→ Önce teslim et, ödeme takip eder' },
        { icon: '⏱️', title: '90 gün aksiyon kuralı', desc: 'Bütçe görüşmesinin ardından 30/60/90. günlerde otomatik uyarı. 90. günde aksiyonsuz kalırsa ilan askıya alınır ve taahhüt bedeli tutulur.', eff: '→ Ölü ilan açmanın maliyeti var' },
        { icon: '⭐', title: 'Çözüm üretici itibar kilidi', desc: 'Doğrulanmış rozet, referans puanı ve öncelikli eşleşme platforma özgüdür. Platformu atlayan bu birikimini kalıcı olarak kaybeder.', eff: '→ Ayrılmanın uzun vadeli maliyeti' },
      ],
      cta_tag: 'NeedBridge\'e katılın',
      cta_h: 'İlk üyeler arasında olun.',
      cta_em: 'Ekim 2026\'ya kadar ücretsiz.',
      cta_d: 'Yeni bir şey inşa ediyoruz. Büyürken her özellik ücretsiz. Kredi kartı yok, taahhüt yok — Şirket veya Çözüm Üretici olarak katılın ve bugün bağlanmaya başlayın.',
      cta_role_s: '🏢 Ben bir Şirketim',
      cta_role_sv: '🚀 Ben bir Çözüm Üreticiyim',
      cta_btn: 'Ücretsiz katıl →',
      cta_note: 'Ekim 2026\'ya kadar ücretsiz · Spam yok · İstediğinizde iptal',
    },
    problems: {
      eyebrow: 'Problem Panosu',
      h1: 'Gerçek problemler.',
      h1em: 'Çözüme açık.',
      desc: 'Şirketler tedarik ihtiyaçlarını anonim olarak yayınlar. Her ilanın bütçesi, son tarihi ve çözüm tipi bellidir. Tüm ilanları görmek ve başvurmak için Çözüm Üretici olarak katılın.',
      example_notice: 'Bunlar platformun nasıl çalıştığını göstermek için hazırlanmış örnek ilanlardır. Şirketler katıldığında gerçek ilanlar yayınlanır.',
      filter_placeholder: 'İlan, sektör veya teknoloji ara...',
      all: 'Tümü',
      paywall_title: 'Tüm ilanları görmek için Çözüm Üretici olarak katılın',
      paywall_sub: 'Ekim 2026\'ya kadar ücretsiz. Göz atın, başvurun, bağlanın.',
      paywall_btn: 'Ücretsiz Çözüm Üretici olarak katıl →',
      apply_btn: 'Detaylar & Başvur',
      save_btn: 'Kaydet',
      apps: 'başvuru',
      pilot_ok: 'Pilot OK',
      seeker_box_title: 'Siz bir Şirket misiniz?',
      seeker_box_desc: 'Tedarik probleminizi yayınlayın ve yenilikçi startup\'lara ulaşın. Ücretsiz.',
      seeker_box_btn: 'Problem ilanı aç →',
      urgent: 'Acil',
      open: 'Açık',
      review: 'İncelemede',
    },
    solvers: {
      eyebrow: 'Çözüm Üretici Vitrini',
      h1: 'Kurumsal problemleri çözen startup\'lar.',
      h1em: 'Global.',
      desc: 'Çözüm kategorisi, teknoloji ve bölgeye göre startup\'lara göz atın. Bağlantı kurmak için Şirket olarak katılın.',
      example_notice: 'Bunlar platformun nasıl çalıştığını göstermek için hazırlanmış örnek profillerdir. Startup\'lar katıldığında gerçek profiller görünür.',
      add_btn: 'Startup\'ınızı ekleyin →',
      filter_placeholder: 'Çözüm üretici, teknoloji ara...',
      all: 'Tümü',
      new_week: '✨ Bu hafta yeni',
      view: 'Profili gör',
      connect: 'Bağlantı kur',
      verified: '✓ Doğrulanmış',
      paywall_title: 'Çözüm üreticilerle bağlantı kurmak için Şirket olarak katılın',
      paywall_sub: 'Ekim 2026\'ya kadar ücretsiz.',
      paywall_btn: 'Ücretsiz Şirket olarak katıl →',
    },
    join: {
      tag: 'Erken erişim',
      h1: 'Hesabınızı oluşturun',
      sub: 'Ekim 2026\'ya kadar ücretsiz. Kredi kartı gerekmez.',
      left_h: 'Kurumsal problemlerin startup çözümleriyle buluştuğu platform.',
      left_d: 'Şirket olarak katılın ve problemlerinizi anonim yayınlayın. Çözüm Üretici olarak katılın ve doğrulanmış bir itibar oluşturun.',
      tab_solver: '🚀 Ben Çözüm Üreticiyim',
      tab_seeker: '🏢 Ben Şirketim',
      name: 'Ad Soyad',
      email: 'İş e-postası',
      company: 'Şirket / Startup adı',
      cat: 'Birincil çözüm kategorisi',
      sector: 'Sektörünüz',
      country: 'Ülke',
      submit: 'Ücretsiz hesap oluştur →',
      terms: 'Katılarak',
      terms_link: 'Kullanım Şartlarını',
      and: 've',
      privacy_link: 'Gizlilik Politikasını',
      or: 'veya',
      li_btn: 'LinkedIn ile devam et',
      success_h: 'Listedesiniz!',
      success_d: 'NeedBridge erken erişimine hoş geldiniz. 24 saat içinde aktivasyon bağlantısı göndereceğiz.',
      note: 'Ekim 2026\'ya kadar ücretsiz · Spam yok · İstediğinizde iptal',
    },
    pricing: {
      tag: 'Fiyatlandırma',
      h1: 'Ücretsiz başlayın.',
      h1em: 'Birlikte büyüyelim.',
      desc: 'Ekim 2026\'ya kadar herkes için ücretsiz. Sonrasında basit bir model: Şirketler her zaman ücretsiz ilan açar. Çözüm üreticiler bağlanmak için plan seçer.',
      free_alert: '🎉 Erken erişim: Ekim 2026\'ya kadar her özellik ücretsiz. Kredi kartı gerekmez.',
      free_pill: 'Ekim 2026\'ya kadar ücretsiz',
      monthly: 'Aylık',
      annual: 'Yıllık',
      save: '%20 tasarruf',
      tab_solver: '🚀 Çözüm Üretici planları',
      tab_seeker: '🏢 Şirket planları',
    },
  },
};

let currentLang = localStorage.getItem('nb_lang') || 'en';

function t(path) {
  const parts = path.split('.');
  let val = LANG[currentLang];
  for (const p of parts) { val = val?.[p]; }
  return val ?? path;
}

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('nb_lang', lang);
  document.querySelectorAll('.lang-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.lang === lang);
  });
  if (typeof applyLang === 'function') applyLang();
}

function initLang() {
  document.querySelectorAll('.lang-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.lang === currentLang);
    b.onclick = () => setLang(b.dataset.lang);
  });
}
